export type Platform = {
  key: string
  label: string
}

const PLATFORMS: Array<{hosts: string[]; platform: Platform}> = [
  {hosts: ['youtube.com', 'youtu.be', 'music.youtube.com'], platform: {key: 'youtube', label: 'YouTube'}},
  {hosts: ['x.com', 'twitter.com'], platform: {key: 'x', label: 'X / Twitter'}},
  {hosts: ['instagram.com'], platform: {key: 'instagram', label: 'Instagram'}},
  {hosts: ['threads.net', 'threads.com'], platform: {key: 'threads', label: 'Threads'}},
  {hosts: ['tiktok.com'], platform: {key: 'tiktok', label: 'TikTok'}},
  {hosts: ['vimeo.com'], platform: {key: 'vimeo', label: 'Vimeo'}},
  {hosts: ['twitch.tv'], platform: {key: 'twitch', label: 'Twitch'}},
  {hosts: ['reddit.com', 'redd.it'], platform: {key: 'reddit', label: 'Reddit'}},
  {hosts: ['facebook.com', 'fb.watch', 'fb.com'], platform: {key: 'facebook', label: 'Facebook'}},
  {hosts: ['soundcloud.com'], platform: {key: 'soundcloud', label: 'SoundCloud'}},
  {hosts: ['spotify.com', 'open.spotify.com'], platform: {key: 'spotify', label: 'Spotify'}},
  {hosts: ['bandcamp.com'], platform: {key: 'bandcamp', label: 'Bandcamp'}},
  {hosts: ['dailymotion.com', 'dai.ly'], platform: {key: 'dailymotion', label: 'Dailymotion'}},
  {hosts: ['bilibili.com', 'b23.tv'], platform: {key: 'bilibili', label: 'Bilibili'}},
  {hosts: ['pinterest.com', 'pin.it'], platform: {key: 'pinterest', label: 'Pinterest'}},
  {hosts: ['tumblr.com'], platform: {key: 'tumblr', label: 'Tumblr'}},
  {hosts: ['ok.ru', 'odnoklassniki.ru'], platform: {key: 'ok', label: 'OK.ru'}},
  {hosts: ['streamable.com'], platform: {key: 'streamable', label: 'Streamable'}},
  // Streaming hosts / embedded players
  {hosts: ['streamtape.com', 'streamtape.net', 'streamtape.to'], platform: {key: 'streamtape', label: 'StreamTape'}},
  {hosts: ['mixdrop.co', 'mixdrop.to', 'mixdrop.sx'], platform: {key: 'mixdrop', label: 'MixDrop'}},
  {hosts: ['dood.to', 'dood.so', 'dood.ws', 'dood.sh', 'dood.re'], platform: {key: 'doodstream', label: 'DoodStream'}},
  {hosts: ['filemoon.sx', 'filemoon.to', 'filemoon.in'], platform: {key: 'filemoon', label: 'FileMoon'}},
  {hosts: ['voe.sx'], platform: {key: 'voe', label: 'VOE'}},
  {hosts: ['vidcloud.co', 'vidcloud.pro'], platform: {key: 'vidcloud', label: 'VidCloud'}},
  {hosts: ['upstream.to'], platform: {key: 'upstream', label: 'UpStream'}},
  {hosts: ['streamhub.to'], platform: {key: 'streamhub', label: 'StreamHub'}},
  {hosts: ['embed.smashystream.com', 'smashystream.com'], platform: {key: 'smashy', label: 'SmashyStream'}},
  // More streaming / video hosts
  {hosts: ['vidsrc.to', 'vidsrc.me', 'vidsrc.net', 'vidsrc.xyz'], platform: {key: 'vidsrc', label: 'VidSrc'}},
  {hosts: ['embed.su', 'embed.su'], platform: {key: 'embedsu', label: 'Embed.su'}},
  {hosts: ['mega.nz', 'mega.co.nz'], platform: {key: 'mega', label: 'MEGA'}},
  {hosts: ['drive.google.com'], platform: {key: 'gdrive', label: 'Google Drive'}},
  {hosts: ['dropbox.com', 'dl.dropboxusercontent.com'], platform: {key: 'dropbox', label: 'Dropbox'}},
  {hosts: ['onedrive.live.com', '1drv.ms'], platform: {key: 'onedrive', label: 'OneDrive'}},
  {hosts: ['mediafire.com'], platform: {key: 'mediafire', label: 'MediaFire'}},
  {hosts: ['archive.org'], platform: {key: 'archive', label: 'Internet Archive'}},
  {hosts: ['rumble.com'], platform: {key: 'rumble', label: 'Rumble'}},
  {hosts: ['odysee.com', 'lbry.tv'], platform: {key: 'odysee', label: 'Odysee'}},
  {hosts: ['bitchute.com'], platform: {key: 'bitchute', label: 'BitChute'}},
  {hosts: ['peertube.tv', 'peertube.social'], platform: {key: 'peertube', label: 'PeerTube'}},
  {hosts: ['niconico.jp', 'nicovideo.jp'], platform: {key: 'niconico', label: 'Niconico'}},
  {hosts: ['crunchyroll.com'], platform: {key: 'crunchyroll', label: 'Crunchyroll'}},
  {hosts: ['funimation.com'], platform: {key: 'funimation', label: 'Funimation'}},
  {hosts: ['pluto.tv'], platform: {key: 'pluto', label: 'Pluto TV'}},
  {hosts: ['tubi.tv', 'tubitv.com'], platform: {key: 'tubi', label: 'Tubi'}},
  {hosts: ['viki.com'], platform: {key: 'viki', label: 'Viki'}},
  {hosts: ['weverse.io'], platform: {key: 'weverse', label: 'Weverse'}},
  {hosts: ['vlive.tv'], platform: {key: 'vlive', label: 'V Live'}},
  {hosts: ['likee.video', 'likee.com'], platform: {key: 'likee', label: 'Likee'}},
  {hosts: ['kwai.com', 'kwaicdn.com'], platform: {key: 'kwai', label: 'Kwai'}},
  {hosts: ['snapchat.com'], platform: {key: 'snapchat', label: 'Snapchat'}},
  {hosts: ['telegram.org', 't.me'], platform: {key: 'telegram', label: 'Telegram'}},
  {hosts: ['discord.com', 'discordapp.com'], platform: {key: 'discord', label: 'Discord'}},
  {hosts: ['whatsapp.com'], platform: {key: 'whatsapp', label: 'WhatsApp'}},
  // Music platforms
  {hosts: ['music.apple.com'], platform: {key: 'applemusic', label: 'Apple Music'}},
  {hosts: ['deezer.com'], platform: {key: 'deezer', label: 'Deezer'}},
  {hosts: ['tidal.com'], platform: {key: 'tidal', label: 'Tidal'}},
  {hosts: ['music.amazon.com', 'amazon.com'], platform: {key: 'amazonmusic', label: 'Amazon Music'}},
  {hosts: ['audiomack.com'], platform: {key: 'audiomack', label: 'Audiomack'}},
  {hosts: ['reverbnation.com'], platform: {key: 'reverbnation', label: 'ReverbNation'}},
  {hosts: ['last.fm', 'lastfm.com'], platform: {key: 'lastfm', label: 'Last.fm'}},
  // Short video / social
  {hosts: ['youtube.com', 'youtu.be', 'music.youtube.com', 'studio.youtube.com'], platform: {key: 'youtube', label: 'YouTube'}},
  {hosts: ['shorts.youtube.com'], platform: {key: 'youtube', label: 'YouTube Shorts'}},
  {hosts: ['clipchamp.com'], platform: {key: 'clipchamp', label: 'Clipchamp'}},
  {hosts: ['capcut.com'], platform: {key: 'capcut', label: 'CapCut'}},
  // Anime / Asian content
  {hosts: ['aniwatch.to', 'aniwatchtv.to'], platform: {key: 'aniwatch', label: 'AniWatch'}},
  {hosts: ['gogoanime.tv', 'gogoanimehd.to'], platform: {key: 'gogoanime', label: 'GogoAnime'}},
  {hosts: ['9anime.to', '9animetv.to'], platform: {key: '9anime', label: '9Anime'}},
  {hosts: ['animepahe.com', 'animepahe.ru'], platform: {key: 'animepahe', label: 'AnimePahe'}},
  {hosts: ['myanimelist.net'], platform: {key: 'mal', label: 'MyAnimeList'}},
  {hosts: ['anilist.co'], platform: {key: 'anilist', label: 'AniList'}},
  // File hosting / direct
  {hosts: ['zippyshare.com'], platform: {key: 'zippyshare', label: 'ZippyShare'}},
  {hosts: ['fembed.com', 'femax20.com'], platform: {key: 'fembed', label: 'Fembed'}},
  {hosts: ['mp4upload.com'], platform: {key: 'mp4upload', label: 'Mp4Upload'}},
  {hosts: ['yourupload.com'], platform: {key: 'yourupload', label: 'YourUpload'}},
  {hosts: ['vidlox.me', 'vidlox.tv'], platform: {key: 'vidlox', label: 'VidLox'}},
  {hosts: ['gofile.io'], platform: {key: 'gofile', label: 'GoFile'}},
  {hosts: ['anonfiles.com'], platform: {key: 'anonfiles', label: 'AnonFiles'}},
  {hosts: ['transfer.sh'], platform: {key: 'transfersh', label: 'transfer.sh'}},
  {hosts: ['catbox.moe', 'files.catbox.moe'], platform: {key: 'catbox', label: 'Catbox'}},
  {hosts: ['litterbox.catbox.moe'], platform: {key: 'litterbox', label: 'Litterbox'}},
  // Live streaming
  {hosts: ['kick.com'], platform: {key: 'kick', label: 'Kick'}},
  {hosts: ['trovo.live'], platform: {key: 'trovo', label: 'Trovo'}},
  {hosts: ['dlive.tv'], platform: {key: 'dlive', label: 'DLive'}},
  {hosts: ['picarto.tv'], platform: {key: 'picarto', label: 'Picarto'}},
  {hosts: ['goodgame.ru'], platform: {key: 'goodgame', label: 'GoodGame'}},
  // Misc
  {hosts: ['tiktok.com', 'vm.tiktok.com', 'vt.tiktok.com'], platform: {key: 'tiktok', label: 'TikTok'}},
  {hosts: ['instagram.com', 'instagr.am'], platform: {key: 'instagram', label: 'Instagram'}},
  {hosts: ['facebook.com', 'fb.watch', 'fb.com', 'm.facebook.com', 'web.facebook.com'], platform: {key: 'facebook', label: 'Facebook'}},
  {hosts: ['x.com', 'twitter.com', 'mobile.twitter.com'], platform: {key: 'x', label: 'X / Twitter'}},
  {hosts: ['reddit.com', 'redd.it', 'old.reddit.com', 'www.reddit.com'], platform: {key: 'reddit', label: 'Reddit'}},
  {hosts: ['vimeo.com', 'player.vimeo.com'], platform: {key: 'vimeo', label: 'Vimeo'}},
  {hosts: ['dailymotion.com', 'dai.ly', 'geo.dailymotion.com'], platform: {key: 'dailymotion', label: 'Dailymotion'}},
  {hosts: ['twitch.tv', 'clips.twitch.tv', 'player.twitch.tv'], platform: {key: 'twitch', label: 'Twitch'}},
  {hosts: ['soundcloud.com', 'm.soundcloud.com', 'on.soundcloud.com'], platform: {key: 'soundcloud', label: 'SoundCloud'}},
  {hosts: ['mixcloud.com'], platform: {key: 'mixcloud', label: 'Mixcloud'}},
  {hosts: ['hearthis.at'], platform: {key: 'hearthis', label: 'hearthis.at'}},
  {hosts: ['clyp.it'], platform: {key: 'clyp', label: 'Clyp'}},
  {hosts: ['vocaroo.com'], platform: {key: 'vocaroo', label: 'Vocaroo'}},
  {hosts: ['voca.ro'], platform: {key: 'vocaroo', label: 'Vocaroo'}},
  // Podcast / audio
  {hosts: ['podbean.com'], platform: {key: 'podbean', label: 'Podbean'}},
  {hosts: ['anchor.fm', 'spotify.com'], platform: {key: 'anchor', label: 'Anchor/Spotify'}},
  {hosts: ['podcasts.apple.com'], platform: {key: 'applepodcasts', label: 'Apple Podcasts'}},
  {hosts: ['overcast.fm'], platform: {key: 'overcast', label: 'Overcast'}},
  {hosts: ['pocketcasts.com'], platform: {key: 'pocketcasts', label: 'Pocket Casts'}},
  // Educational / other
  {hosts: ['coursera.org'], platform: {key: 'coursera', label: 'Coursera'}},
  {hosts: ['udemy.com'], platform: {key: 'udemy', label: 'Udemy'}},
  {hosts: ['skillshare.com'], platform: {key: 'skillshare', label: 'Skillshare'}},
  {hosts: ['ted.com', 'tedx.com'], platform: {key: 'ted', label: 'TED'}},
  {hosts: ['khanacademy.org'], platform: {key: 'khan', label: 'Khan Academy'}},
  {hosts: ['linkedin.com', 'linkedin.com'], platform: {key: 'linkedin', label: 'LinkedIn'}},
  {hosts: ['slideshare.net'], platform: {key: 'slideshare', label: 'SlideShare'}},
  {hosts: ['scribd.com'], platform: {key: 'scribd', label: 'Scribd'}},
  {hosts: ['issuu.com'], platform: {key: 'issuu', label: 'Issuu'}},
  // News / media
  {hosts: ['cnn.com'], platform: {key: 'cnn', label: 'CNN'}},
  {hosts: ['bbc.com', 'bbc.co.uk'], platform: {key: 'bbc', label: 'BBC'}},
  {hosts: ['nytimes.com'], platform: {key: 'nytimes', label: 'NY Times'}},
  {hosts: ['washingtonpost.com'], platform: {key: 'wapo', label: 'Washington Post'}},
  {hosts: ['theguardian.com'], platform: {key: 'guardian', label: 'The Guardian'}},
  {hosts: ['aljazeera.com'], platform: {key: 'aljazeera', label: 'Al Jazeera'}},
  {hosts: ['reuters.com'], platform: {key: 'reuters', label: 'Reuters'}},
  {hosts: ['bloomberg.com'], platform: {key: 'bloomberg', label: 'Bloomberg'}},
  {hosts: ['cnbc.com'], platform: {key: 'cnbc', label: 'CNBC'}},
  {hosts: ['foxnews.com'], platform: {key: 'foxnews', label: 'Fox News'}},
  {hosts: ['msnbc.com'], platform: {key: 'msnbc', label: 'MSNBC'}},
  {hosts: ['abcnews.go.com'], platform: {key: 'abcnews', label: 'ABC News'}},
  {hosts: ['cbsnews.com'], platform: {key: 'cbsnews', label: 'CBS News'}},
  {hosts: ['nbcnews.com'], platform: {key: 'nbcnews', label: 'NBC News'}},
  {hosts: ['usatoday.com'], platform: {key: 'usatoday', label: 'USA Today'}},
  {hosts: ['apnews.com'], platform: {key: 'apnews', label: 'AP News'}},
  {hosts: ['dw.com'], platform: {key: 'dw', label: 'DW'}},
  {hosts: ['france24.com'], platform: {key: 'france24', label: 'France 24'}},
  {hosts: ['rt.com'], platform: {key: 'rt', label: 'RT'}},
  {hosts: ['sputniknews.com'], platform: {key: 'sputnik', label: 'Sputnik'}},
  {hosts: ['nhk.or.jp'], platform: {key: 'nhk', label: 'NHK'}},
  {hosts: ['cctv.com'], platform: {key: 'cctv', label: 'CCTV'}},
  {hosts: ['kompas.com', 'kompas.tv'], platform: {key: 'kompas', label: 'Kompas'}},
  {hosts: ['detik.com'], platform: {key: 'detik', label: 'Detik'}},
  {hosts: ['tribunnews.com'], platform: {key: 'tribun', label: 'Tribunnews'}},
  {hosts: ['cnnindonesia.com'], platform: {key: 'cnnid', label: 'CNN Indonesia'}},
  {hosts: ['tvonenews.com'], platform: {key: 'tvone', label: 'tvOne'}},
  {hosts: ['metrotvnews.com'], platform: {key: 'metrotv', label: 'Metro TV'}},
  {hosts: ['liputan6.com'], platform: {key: 'liputan6', label: 'Liputan6'}},
  {hosts: ['tempo.co'], platform: {key: 'tempo', label: 'Tempo'}},
  {hosts: ['antaranews.com'], platform: {key: 'antara', label: 'Antara'}},
  {hosts: ['republika.co.id'], platform: {key: 'republika', label: 'Republika'}},
  {hosts: ['suara.com'], platform: {key: 'suara', label: 'Suara'}},
  {hosts: ['okezone.com'], platform: {key: 'okezone', label: 'Okezone'}},
  {hosts: ['sindonews.com'], platform: {key: 'sindo', label: 'SindoNews'}},
  {hosts: ['inews.id'], platform: {key: 'inews', label: 'iNews'}},
  {hosts: ['beritasatu.com'], platform: {key: 'beritasatu', label: 'BeritaSatu'}},
  {hosts: ['idntimes.com'], platform: {key: 'idntimes', label: 'IDN Times'}},
  {hosts: ['kumparan.com'], platform: {key: 'kumparan', label: 'Kumparan'}},
  {hosts: ['brilio.net'], platform: {key: 'brilio', label: 'Brilio'}},
  {hosts: ['merdeka.com'], platform: {key: 'merdeka', label: 'Merdeka'}},
  {hosts: ['viva.co.id'], platform: {key: 'viva', label: 'Viva'}},
  {hosts: ['dream.co.id'], platform: {key: 'dream', label: 'Dream'}},
  {hosts: ['bola.com', 'bolanet.com'], platform: {key: 'bola', label: 'Bola'}},
  {hosts: ['sport.detik.com'], platform: {key: 'detiksport', label: 'Detik Sport'}},
  {hosts: ['goal.com'], platform: {key: 'goal', label: 'Goal'}},
  {hosts: ['espn.com'], platform: {key: 'espn', label: 'ESPN'}},
  {hosts: ['bleacherreport.com'], platform: {key: 'br', label: 'Bleacher Report'}},
  {hosts: ['skysports.com'], platform: {key: 'skysports', label: 'Sky Sports'}},
  {hosts: ['beinsports.com'], platform: {key: 'bein', label: 'beIN Sports'}},
  {hosts: ['fifa.com'], platform: {key: 'fifa', label: 'FIFA'}},
  {hosts: ['uefa.com'], platform: {key: 'uefa', label: 'UEFA'}},
  {hosts: ['nba.com'], platform: {key: 'nba', label: 'NBA'}},
  {hosts: ['nfl.com'], platform: {key: 'nfl', label: 'NFL'}},
  {hosts: ['mlb.com'], platform: {key: 'mlb', label: 'MLB'}},
  {hosts: ['nhl.com'], platform: {key: 'nhl', label: 'NHL'}},
  {hosts: ['f1.com', 'formula1.com'], platform: {key: 'f1', label: 'F1'}},
  {hosts: ['motogp.com'], platform: {key: 'motogp', label: 'MotoGP'}},
  {hosts: ['wwe.com'], platform: {key: 'wwe', label: 'WWE'}},
  {hosts: ['ufc.com'], platform: {key: 'ufc', label: 'UFC'}},
  {hosts: ['dazn.com'], platform: {key: 'dazn', label: 'DAZN'}},
  {hosts: ['espnplus.com'], platform: {key: 'espnplus', label: 'ESPN+'}},
  {hosts: ['paramountplus.com'], platform: {key: 'paramount', label: 'Paramount+'}},
  {hosts: ['peacocktv.com'], platform: {key: 'peacock', label: 'Peacock'}},
  {hosts: ['hulu.com'], platform: {key: 'hulu', label: 'Hulu'}},
  {hosts: ['disneyplus.com', 'disney.plus.com'], platform: {key: 'disneyplus', label: 'Disney+'}},
  {hosts: ['hbomax.com', 'max.com'], platform: {key: 'hbomax', label: 'HBO Max'}},
  {hosts: ['primevideo.com', 'amazon.com'], platform: {key: 'primevideo', label: 'Prime Video'}},
  {hosts: ['netflix.com'], platform: {key: 'netflix', label: 'Netflix'}},
  {hosts: ['apple.com', 'tv.apple.com'], platform: {key: 'appletv', label: 'Apple TV'}},
  {hosts: ['mubi.com'], platform: {key: 'mubi', label: 'Mubi'}},
  {hosts: ['crackle.com'], platform: {key: 'crackle', label: 'Crackle'}},
  {hosts: ['pluto.tv'], platform: {key: 'pluto', label: 'Pluto TV'}},
  {hosts: ['imdb.com'], platform: {key: 'imdb', label: 'IMDb'}},
  {hosts: ['rottentomatoes.com'], platform: {key: 'rt', label: 'Rotten Tomatoes'}},
  {hosts: ['metacritic.com'], platform: {key: 'metacritic', label: 'Metacritic'}},
  {hosts: ['letterboxd.com'], platform: {key: 'letterboxd', label: 'Letterboxd'}},
  {hosts: ['trakt.tv'], platform: {key: 'trakt', label: 'Trakt'}},
  {hosts: ['simkl.com'], platform: {key: 'simkl', label: 'Simkl'}},
  {hosts: ['justwatch.com'], platform: {key: 'justwatch', label: 'JustWatch'}},
  {hosts: ['reelgood.com'], platform: {key: 'reelgood', label: 'Reelgood'}},
  {hosts: ['tvtime.com'], platform: {key: 'tvtime', label: 'TV Time'}},
  {hosts: ['serializd.com'], platform: {key: 'serializd', label: 'Serializd'}},
  {hosts: ['thetvdb.com'], platform: {key: 'thetvdb', label: 'TheTVDB'}},
  {hosts: ['themoviedb.org'], platform: {key: 'tmdb', label: 'TMDB'}},
  {hosts: ['fanart.tv'], platform: {key: 'fanart', label: 'Fanart'}},
  {hosts: ['posterdb.com'], platform: {key: 'posterdb', label: 'PosterDB'}},
  {hosts: ['imagebam.com'], platform: {key: 'imagebam', label: 'ImageBam'}},
  {hosts: ['imgur.com', 'i.imgur.com'], platform: {key: 'imgur', label: 'Imgur'}},
  {hosts: ['gfycat.com'], platform: {key: 'gfycat', label: 'Gfycat'}},
  {hosts: ['redgifs.com'], platform: {key: 'redgifs', label: 'RedGIFs'}},
  {hosts: ['giphy.com', 'media.giphy.com'], platform: {key: 'giphy', label: 'GIPHY'}},
  {hosts: ['tenor.com', 'media.tenor.com'], platform: {key: 'tenor', label: 'Tenor'}},
  {hosts: ['streamja.com'], platform: {key: 'streamja', label: 'Streamja'}},
  {hosts: ['streamsb.net', 'streamsb.com'], platform: {key: 'streamsb', label: 'StreamSB'}},
  {hosts: ['vidoza.net'], platform: {key: 'vidoza', label: 'Vidoza'}},
  {hosts: ['uptostream.com', 'uptobox.com'], platform: {key: 'uptobox', label: 'Uptobox'}},
  {hosts: ['1fichier.com'], platform: {key: '1fichier', label: '1fichier'}},
  {hosts: ['rapidgator.net'], platform: {key: 'rapidgator', label: 'Rapidgator'}},
  {hosts: ['nitroflare.com'], platform: {key: 'nitroflare', label: 'NitroFlare'}},
  {hosts: ['turbobit.net'], platform: {key: 'turbobit', label: 'TurboBit'}},
  {hosts: ['uploaded.net', 'uploaded.to'], platform: {key: 'uploaded', label: 'Uploaded'}},
  {hosts: ['filefactory.com'], platform: {key: 'filefactory', label: 'FileFactory'}},
  {hosts: ['file.al'], platform: {key: 'fileal', label: 'File.al'}},
  {hosts: ['hexupload.net'], platform: {key: 'hexupload', label: 'HexUpload'}},
  {hosts: ['doodstream.com'], platform: {key: 'doodstream', label: 'DoodStream'}},
  {hosts: ['vidbom.com'], platform: {key: 'vidbom', label: 'VidBom'}},
  {hosts: ['vidshare.tv'], platform: {key: 'vidshare', label: 'VidShare'}},
  {hosts: ['myvi.ru'], platform: {key: 'myvi', label: 'Myvi'}},
  {hosts: ['rutube.ru'], platform: {key: 'rutube', label: 'Rutube'}},
  {hosts: ['vk.com', 'vkontakte.ru'], platform: {key: 'vk', label: 'VK'}},
  {hosts: ['ok.ru'], platform: {key: 'ok', label: 'OK.ru'}},
  {hosts: ['yandex.ru', 'kinopoisk.ru'], platform: {key: 'yandex', label: 'Yandex'}},
  {hosts: ['mail.ru', 'my.mail.ru'], platform: {key: 'mailru', label: 'Mail.ru'}},
  {hosts: ['rambler.ru'], platform: {key: 'rambler', label: 'Rambler'}},
  {hosts: ['ivi.ru'], platform: {key: 'ivi', label: 'Ivi'}},
  {hosts: ['megogo.net'], platform: {key: 'megogo', label: 'Megogo'}},
  {hosts: ['smotrim.ru'], platform: {key: 'smotrim', label: 'Smotrim'}},
  {hosts: ['1tv.ru'], platform: {key: '1tv', label: 'Channel One'}},
  {hosts: ['ntv.ru'], platform: {key: 'ntv', label: 'NTV'}},
  {hosts: ['ren.tv'], platform: {key: 'rentv', label: 'REN TV'}},
  {hosts: ['sts.ru'], platform: {key: 'sts', label: 'STS'}},
  {hosts: ['tnt-online.ru'], platform: {key: 'tnt', label: 'TNT'}},
  {hosts: ['domashniy.ru'], platform: {key: 'domashniy', label: 'Domashniy'}},
  {hosts: ['zvezda.ru'], platform: {key: 'zvezda', label: 'Zvezda'}},
  {hosts: ['mir24.tv'], platform: {key: 'mir24', label: 'Mir24'}},
  {hosts: ['tvzvezda.ru'], platform: {key: 'tvzvezda', label: 'TV Zvezda'}},
  {hosts: ['matchtv.ru'], platform: {key: 'matchtv', label: 'Match TV'}},
  {hosts: ['sportbox.ru'], platform: {key: 'sportbox', label: 'Sportbox'}},
  {hosts: ['championat.com'], platform: {key: 'championat', label: 'Championat'}},
  {hosts: ['sports.ru'], platform: {key: 'sportsru', label: 'Sports.ru'}},
  {hosts: ['sovsport.ru'], platform: {key: 'sovsport', label: 'SovSport'}},
  {hosts: ['rsport.ria.ru'], platform: {key: 'rsport', label: 'R-Sport'}},
  {hosts: ['tass.ru'], platform: {key: 'tass', label: 'TASS'}},
  {hosts: ['ria.ru'], platform: {key: 'ria', label: 'RIA'}},
  {hosts: ['interfax.ru'], platform: {key: 'interfax', label: 'Interfax'}},
  {hosts: ['rbc.ru'], platform: {key: 'rbc', label: 'RBC'}},
  {hosts: ['kommersant.ru'], platform: {key: 'kommersant', label: 'Kommersant'}},
  {hosts: ['vedomosti.ru'], platform: {key: 'vedomosti', label: 'Vedomosti'}},
  {hosts: ['gazeta.ru'], platform: {key: 'gazeta', label: 'Gazeta.ru'}},
  {hosts: ['lenta.ru'], platform: {key: 'lenta', label: 'Lenta.ru'}},
  {hosts: ['mk.ru'], platform: {key: 'mk', label: 'MK'}},
  {hosts: ['kp.ru'], platform: {key: 'kp', label: 'KP'}},
  {hosts: ['aif.ru'], platform: {key: 'aif', label: 'AiF'}},
  {hosts: ['rg.ru'], platform: {key: 'rg', label: 'RG'}},
  {hosts: ['iz.ru'], platform: {key: 'iz', label: 'IZ'}},
  {hosts: ['vz.ru'], platform: {key: 'vz', label: 'VZ'}},
  {hosts: ['regnum.ru'], platform: {key: 'regnum', label: 'Regnum'}},
  {hosts: ['rosbalt.ru'], platform: {key: 'rosbalt', label: 'Rosbalt'}},
  {hosts: ['fontanka.ru'], platform: {key: 'fontanka', label: 'Fontanka'}},
  {hosts: ['neva.today'], platform: {key: 'neva', label: 'Neva'}},
  {hosts: ['mr-7.ru'], platform: {key: 'mr7', label: 'MR7'}},
  {hosts: ['dp.ru'], platform: {key: 'dp', label: 'DP'}},
  {hosts: ['baltika7.ru'], platform: {key: 'baltika', label: 'Baltika'}},
  {hosts: ['peterburg2.ru'], platform: {key: 'peterburg2', label: 'Peterburg2'}},
  {hosts: ['gorod55.ru'], platform: {key: 'gorod55', label: 'Gorod55'}},
  {hosts: ['ngs.ru'], platform: {key: 'ngs', label: 'NGS'}},
  {hosts: ['e1.ru'], platform: {key: 'e1', label: 'E1'}},
  {hosts: ['74.ru'], platform: {key: '74ru', label: '74.ru'}},
  {hosts: ['161.ru'], platform: {key: '161ru', label: '161.ru'}},
  {hosts: ['63.ru'], platform: {key: '63ru', label: '63.ru'}},
  {hosts: ['59.ru'], platform: {key: '59ru', label: '59.ru'}},
  {hosts: ['43.ru'], platform: {key: '43ru', label: '43.ru'}},
  {hosts: ['35.ru'], platform: {key: '35ru', label: '35.ru'}},
  {hosts: ['29.ru'], platform: {key: '29ru', label: '29.ru'}},
  {hosts: ['14.ru'], platform: {key: '14ru', label: '14.ru'}},
  {hosts: ['116.ru'], platform: {key: '116ru', label: '116.ru'}},
  {hosts: ['prokazan.ru'], platform: {key: 'prokazan', label: 'ProKazan'}},
  {hosts: ['progorod59.ru'], platform: {key: 'progorod59', label: 'ProGorod59'}},
  {hosts: ['progorodnn.ru'], platform: {key: 'progorodnn', label: 'ProGorodNN'}},
  {hosts: ['progorodsamara.ru'], platform: {key: 'progorodsamara', label: 'ProGorodSamara'}},
  {hosts: ['progorod76.ru'], platform: {key: 'progorod76', label: 'ProGorod76'}},
  {hosts: ['progorod43.ru'], platform: {key: 'progorod43', label: 'ProGorod43'}},
  {hosts: ['progorod33.ru'], platform: {key: 'progorod33', label: 'ProGorod33'}},
  {hosts: ['progorod21.ru'], platform: {key: 'progorod21', label: 'ProGorod21'}},
  {hosts: ['progorod12.ru'], platform: {key: 'progorod12', label: 'ProGorod12'}},
  {hosts: ['progorod58.ru'], platform: {key: 'progorod58', label: 'ProGorod58'}},
  {hosts: ['progorod62.ru'], platform: {key: 'progorod62', label: 'ProGorod62'}},
  {hosts: ['progorod71.ru'], platform: {key: 'progorod71', label: 'ProGorod71'}},
  {hosts: ['progorod84.ru'], platform: {key: 'progorod84', label: 'ProGorod84'}},
  {hosts: ['progorod91.ru'], platform: {key: 'progorod91', label: 'ProGorod91'}},
  {hosts: ['progorod96.ru'], platform: {key: 'progorod96', label: 'ProGorod96'}},
  {hosts: ['progorod11.ru'], platform: {key: 'progorod11', label: 'ProGorod11'}},
  {hosts: ['progorod22.ru'], platform: {key: 'progorod22', label: 'ProGorod22'}},
  {hosts: ['progorod24.ru'], platform: {key: 'progorod24', label: 'ProGorod24'}},
  {hosts: ['progorod25.ru'], platform: {key: 'progorod25', label: 'ProGorod25'}},
  {hosts: ['progorod26.ru'], platform: {key: 'progorod26', label: 'ProGorod26'}},
  {hosts: ['progorod27.ru'], platform: {key: 'progorod27', label: 'ProGorod27'}},
  {hosts: ['progorod28.ru'], platform: {key: 'progorod28', label: 'ProGorod28'}},
  {hosts: ['progorod29.ru'], platform: {key: 'progorod29', label: 'ProGorod29'}},
  {hosts: ['progorod30.ru'], platform: {key: 'progorod30', label: 'ProGorod30'}},
  {hosts: ['progorod31.ru'], platform: {key: 'progorod31', label: 'ProGorod31'}},
  {hosts: ['progorod32.ru'], platform: {key: 'progorod32', label: 'ProGorod32'}},
  {hosts: ['progorod34.ru'], platform: {key: 'progorod34', label: 'ProGorod34'}},
  {hosts: ['progorod35.ru'], platform: {key: 'progorod35', label: 'ProGorod35'}},
  {hosts: ['progorod36.ru'], platform: {key: 'progorod36', label: 'ProGorod36'}},
  {hosts: ['progorod37.ru'], platform: {key: 'progorod37', label: 'ProGorod37'}},
  {hosts: ['progorod38.ru'], platform: {key: 'progorod38', label: 'ProGorod38'}},
  {hosts: ['progorod39.ru'], platform: {key: 'progorod39', label: 'ProGorod39'}},
  {hosts: ['progorod40.ru'], platform: {key: 'progorod40', label: 'ProGorod40'}},
  {hosts: ['progorod41.ru'], platform: {key: 'progorod41', label: 'ProGorod41'}},
  {hosts: ['progorod42.ru'], platform: {key: 'progorod42', label: 'ProGorod42'}},
  {hosts: ['progorod44.ru'], platform: {key: 'progorod44', label: 'ProGorod44'}},
  {hosts: ['progorod45.ru'], platform: {key: 'progorod45', label: 'ProGorod45'}},
  {hosts: ['progorod46.ru'], platform: {key: 'progorod46', label: 'ProGorod46'}},
  {hosts: ['progorod47.ru'], platform: {key: 'progorod47', label: 'ProGorod47'}},
  {hosts: ['progorod48.ru'], platform: {key: 'progorod48', label: 'ProGorod48'}},
  {hosts: ['progorod49.ru'], platform: {key: 'progorod49', label: 'ProGorod49'}},
  {hosts: ['progorod50.ru'], platform: {key: 'progorod50', label: 'ProGorod50'}},
  {hosts: ['progorod51.ru'], platform: {key: 'progorod51', label: 'ProGorod51'}},
  {hosts: ['progorod52.ru'], platform: {key: 'progorod52', label: 'ProGorod52'}},
  {hosts: ['progorod53.ru'], platform: {key: 'progorod53', label: 'ProGorod53'}},
  {hosts: ['progorod54.ru'], platform: {key: 'progorod54', label: 'ProGorod54'}},
  {hosts: ['progorod55.ru'], platform: {key: 'progorod55', label: 'ProGorod55'}},
  {hosts: ['progorod56.ru'], platform: {key: 'progorod56', label: 'ProGorod56'}},
  {hosts: ['progorod57.ru'], platform: {key: 'progorod57', label: 'ProGorod57'}},
  {hosts: ['progorod60.ru'], platform: {key: 'progorod60', label: 'ProGorod60'}},
  {hosts: ['progorod61.ru'], platform: {key: 'progorod61', label: 'ProGorod61'}},
  {hosts: ['progorod63.ru'], platform: {key: 'progorod63', label: 'ProGorod63'}},
  {hosts: ['progorod64.ru'], platform: {key: 'progorod64', label: 'ProGorod64'}},
  {hosts: ['progorod65.ru'], platform: {key: 'progorod65', label: 'ProGorod65'}},
  {hosts: ['progorod66.ru'], platform: {key: 'progorod66', label: 'ProGorod66'}},
  {hosts: ['progorod67.ru'], platform: {key: 'progorod67', label: 'ProGorod67'}},
  {hosts: ['progorod68.ru'], platform: {key: 'progorod68', label: 'ProGorod68'}},
  {hosts: ['progorod69.ru'], platform: {key: 'progorod69', label: 'ProGorod69'}},
  {hosts: ['progorod70.ru'], platform: {key: 'progorod70', label: 'ProGorod70'}},
  {hosts: ['progorod72.ru'], platform: {key: 'progorod72', label: 'ProGorod72'}},
  {hosts: ['progorod73.ru'], platform: {key: 'progorod73', label: 'ProGorod73'}},
  {hosts: ['progorod74.ru'], platform: {key: 'progorod74', label: 'ProGorod74'}},
  {hosts: ['progorod75.ru'], platform: {key: 'progorod75', label: 'ProGorod75'}},
  {hosts: ['progorod77.ru'], platform: {key: 'progorod77', label: 'ProGorod77'}},
  {hosts: ['progorod78.ru'], platform: {key: 'progorod78', label: 'ProGorod78'}},
  {hosts: ['progorod79.ru'], platform: {key: 'progorod79', label: 'ProGorod79'}},
  {hosts: ['progorod80.ru'], platform: {key: 'progorod80', label: 'ProGorod80'}},
  {hosts: ['progorod81.ru'], platform: {key: 'progorod81', label: 'ProGorod81'}},
  {hosts: ['progorod82.ru'], platform: {key: 'progorod82', label: 'ProGorod82'}},
  {hosts: ['progorod83.ru'], platform: {key: 'progorod83', label: 'ProGorod83'}},
  {hosts: ['progorod85.ru'], platform: {key: 'progorod85', label: 'ProGorod85'}},
  {hosts: ['progorod86.ru'], platform: {key: 'progorod86', label: 'ProGorod86'}},
  {hosts: ['progorod87.ru'], platform: {key: 'progorod87', label: 'ProGorod87'}},
  {hosts: ['progorod88.ru'], platform: {key: 'progorod88', label: 'ProGorod88'}},
  {hosts: ['progorod89.ru'], platform: {key: 'progorod89', label: 'ProGorod89'}},
  {hosts: ['progorod90.ru'], platform: {key: 'progorod90', label: 'ProGorod90'}},
  {hosts: ['progorod92.ru'], platform: {key: 'progorod92', label: 'ProGorod92'}},
  {hosts: ['progorod93.ru'], platform: {key: 'progorod93', label: 'ProGorod93'}},
  {hosts: ['progorod94.ru'], platform: {key: 'progorod94', label: 'ProGorod94'}},
  {hosts: ['progorod95.ru'], platform: {key: 'progorod95', label: 'ProGorod95'}},
  {hosts: ['progorod97.ru'], platform: {key: 'progorod97', label: 'ProGorod97'}},
  {hosts: ['progorod98.ru'], platform: {key: 'progorod98', label: 'ProGorod98'}},
  {hosts: ['progorod99.ru'], platform: {key: 'progorod99', label: 'ProGorod99'}},
  {hosts: ['progorod100.ru'], platform: {key: 'progorod100', label: 'ProGorod100'}},
]

export function detectPlatform(url: string): Platform {
  const trimmed = url.trim()

  // Direct manifest links (HLS / DASH) — common on streaming sites
  if (/\.m3u8(\?|$)/i.test(trimmed)) return {key: 'hls', label: 'HLS Stream (.m3u8)'}
  if (/\.mpd(\?|$)/i.test(trimmed)) return {key: 'dash', label: 'DASH Stream (.mpd)'}
  if (/\.(mp4|mkv|webm|mov|avi)(\?|$)/i.test(trimmed)) return {key: 'direct', label: 'Direct video file'}

  let hostname: string
  try {
    hostname = new URL(trimmed).hostname.toLowerCase()
  } catch {
    return {key: 'unknown', label: 'Unknown site'}
  }

  for (const {hosts, platform} of PLATFORMS) {
    if (hosts.some(h => hostname === h || hostname.endsWith(`.${h}`))) {
      return platform
    }
  }

  return {key: 'generic', label: hostname}
}

export function isProbablyUrl(input: string): boolean {
  try {
    const u = new URL(input.trim())
    return u.protocol === 'http:' || u.protocol === 'https:'
  } catch {
    return false
  }
}